server:
  port: 8080

spring:
  application:
    name: api-service

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    root: WARN
    org.ataraxii.wishlist: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka